//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace UnderstandingReddogDatacenterInfo.BY2 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class MachinePool {
        
        private Vlan[] vlanField;
        
        private string nameField;
        
        private string fCCClusterField;
        
        private string usingSoftwareLoadBalancerOnlyField;
        
        private string torAsRouterField;
        
        private string vipRangeField;
        
        private string capabilitiesField;
        
        private string fillFactorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Vlan")]
        public Vlan[] Vlan {
            get {
                return this.vlanField;
            }
            set {
                this.vlanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FCCCluster {
            get {
                return this.fCCClusterField;
            }
            set {
                this.fCCClusterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UsingSoftwareLoadBalancerOnly {
            get {
                return this.usingSoftwareLoadBalancerOnlyField;
            }
            set {
                this.usingSoftwareLoadBalancerOnlyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TorAsRouter {
            get {
                return this.torAsRouterField;
            }
            set {
                this.torAsRouterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VipRange {
            get {
                return this.vipRangeField;
            }
            set {
                this.vipRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Capabilities {
            get {
                return this.capabilitiesField;
            }
            set {
                this.capabilitiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FillFactor {
            get {
                return this.fillFactorField;
            }
            set {
                this.fillFactorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Vlan {
        
        private VlanRoutingEntry[] routingEntryField;
        
        private VlanIPRange[] iPRangeField;
        
        private VlanMacRange[] macRangeField;
        
        private string nameField;
        
        private string rangeField;
        
        private string routerGatewayField;
        
        private string startIPField;
        
        private string endIPField;
        
        private string tagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RoutingEntry", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VlanRoutingEntry[] RoutingEntry {
            get {
                return this.routingEntryField;
            }
            set {
                this.routingEntryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IPRange", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VlanIPRange[] IPRange {
            get {
                return this.iPRangeField;
            }
            set {
                this.iPRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MacRange", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VlanMacRange[] MacRange {
            get {
                return this.macRangeField;
            }
            set {
                this.macRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Range {
            get {
                return this.rangeField;
            }
            set {
                this.rangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RouterGateway {
            get {
                return this.routerGatewayField;
            }
            set {
                this.routerGatewayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StartIP {
            get {
                return this.startIPField;
            }
            set {
                this.startIPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EndIP {
            get {
                return this.endIPField;
            }
            set {
                this.endIPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class VlanRoutingEntry {
        
        private string rangeField;
        
        private string gatewayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Range {
            get {
                return this.rangeField;
            }
            set {
                this.rangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Gateway {
            get {
                return this.gatewayField;
            }
            set {
                this.gatewayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class VlanIPRange {
        
        private string startIPField;
        
        private string endIPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StartIP {
            get {
                return this.startIPField;
            }
            set {
                this.startIPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EndIP {
            get {
                return this.endIPField;
            }
            set {
                this.endIPField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class VlanMacRange {
        
        private string startMacField;
        
        private string endMacField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StartMac {
            get {
                return this.startMacField;
            }
            set {
                this.startMacField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EndMac {
            get {
                return this.endMacField;
            }
            set {
                this.endMacField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class VIPRange {
        
        private string startIPField;
        
        private string endIPField;
        
        private string subnetField;
        
        private string routerSetNameField;
        
        private string allocationPolicyField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StartIP {
            get {
                return this.startIPField;
            }
            set {
                this.startIPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EndIP {
            get {
                return this.endIPField;
            }
            set {
                this.endIPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Subnet {
            get {
                return this.subnetField;
            }
            set {
                this.subnetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RouterSetName {
            get {
                return this.routerSetNameField;
            }
            set {
                this.routerSetNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AllocationPolicy {
            get {
                return this.allocationPolicyField;
            }
            set {
                this.allocationPolicyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Datacenter {
        
        private MachinePool[] machinePoolField;
        
        private Vlan[] vlanField;
        
        private DatacenterCoreSerialServer[] coreSerialServerField;
        
        private DatacenterRack[] rackField;
        
        private DatacenterRouterSet[] routerSetField;
        
        private DatacenterCluster[] clusterField;
        
        private string locationField;
        
        private string authProxyIpRangeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MachinePool")]
        public MachinePool[] MachinePool {
            get {
                return this.machinePoolField;
            }
            set {
                this.machinePoolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Vlan")]
        public Vlan[] Vlan {
            get {
                return this.vlanField;
            }
            set {
                this.vlanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CoreSerialServer", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DatacenterCoreSerialServer[] CoreSerialServer {
            get {
                return this.coreSerialServerField;
            }
            set {
                this.coreSerialServerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Rack", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DatacenterRack[] Rack {
            get {
                return this.rackField;
            }
            set {
                this.rackField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RouterSet", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DatacenterRouterSet[] RouterSet {
            get {
                return this.routerSetField;
            }
            set {
                this.routerSetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cluster", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DatacenterCluster[] Cluster {
            get {
                return this.clusterField;
            }
            set {
                this.clusterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AuthProxyIpRange {
            get {
                return this.authProxyIpRangeField;
            }
            set {
                this.authProxyIpRangeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DatacenterCoreSerialServer {
        
        private DatacenterCoreSerialServerPort[] portField;
        
        private string locationField;
        
        private string addressField;
        
        private string sKUField;
        
        private string vlanField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Port", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DatacenterCoreSerialServerPort[] Port {
            get {
                return this.portField;
            }
            set {
                this.portField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SKU {
            get {
                return this.sKUField;
            }
            set {
                this.sKUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Vlan {
            get {
                return this.vlanField;
            }
            set {
                this.vlanField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DatacenterCoreSerialServerPort {
        
        private string locationField;
        
        private string connectsToField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ConnectsTo {
            get {
                return this.connectsToField;
            }
            set {
                this.connectsToField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DatacenterRack {
        
        private DatacenterRackNetworkSwitch[] networkSwitchField;
        
        private DatacenterRackSerialServer[] serialServerField;
        
        private DatacenterRackPowerStrip[] powerStripField;
        
        private DatacenterRackBlade[] bladeField;
        
        private string locationField;
        
        private string sKUField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NetworkSwitch", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DatacenterRackNetworkSwitch[] NetworkSwitch {
            get {
                return this.networkSwitchField;
            }
            set {
                this.networkSwitchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SerialServer", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DatacenterRackSerialServer[] SerialServer {
            get {
                return this.serialServerField;
            }
            set {
                this.serialServerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PowerStrip", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DatacenterRackPowerStrip[] PowerStrip {
            get {
                return this.powerStripField;
            }
            set {
                this.powerStripField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Blade", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DatacenterRackBlade[] Blade {
            get {
                return this.bladeField;
            }
            set {
                this.bladeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SKU {
            get {
                return this.sKUField;
            }
            set {
                this.sKUField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DatacenterRackNetworkSwitch {
        
        private string locationField;
        
        private string addressField;
        
        private string vlanField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Vlan {
            get {
                return this.vlanField;
            }
            set {
                this.vlanField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DatacenterRackSerialServer {
        
        private string locationField;
        
        private string addressField;
        
        private string vlanField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Vlan {
            get {
                return this.vlanField;
            }
            set {
                this.vlanField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DatacenterRackPowerStrip {
        
        private string locationField;
        
        private string addressField;
        
        private string vlanField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Vlan {
            get {
                return this.vlanField;
            }
            set {
                this.vlanField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DatacenterRackBlade {
        
        private string locationField;
        
        private string machinePoolField;
        
        private string bladeIPField;
        
        private string bladeIdField;
        
        private string assetField;
        
        private string nIC1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MachinePool {
            get {
                return this.machinePoolField;
            }
            set {
                this.machinePoolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BladeIP {
            get {
                return this.bladeIPField;
            }
            set {
                this.bladeIPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BladeId {
            get {
                return this.bladeIdField;
            }
            set {
                this.bladeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Asset {
            get {
                return this.assetField;
            }
            set {
                this.assetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NIC1 {
            get {
                return this.nIC1Field;
            }
            set {
                this.nIC1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DatacenterRouterSet {
        
        private VIPRange[] vIPRangeField;
        
        private DatacenterRouterSetRouter[] routerField;
        
        private string nameField;
        
        private string sKUField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VIPRange")]
        public VIPRange[] VIPRange {
            get {
                return this.vIPRangeField;
            }
            set {
                this.vIPRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Router", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DatacenterRouterSetRouter[] Router {
            get {
                return this.routerField;
            }
            set {
                this.routerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SKU {
            get {
                return this.sKUField;
            }
            set {
                this.sKUField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DatacenterRouterSetRouter {
        
        private string nameField;
        
        private string locationField;
        
        private string peeringEndpointField;
        
        private string routerASField;
        
        private string peeringASField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PeeringEndpoint {
            get {
                return this.peeringEndpointField;
            }
            set {
                this.peeringEndpointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RouterAS {
            get {
                return this.routerASField;
            }
            set {
                this.routerASField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PeeringAS {
            get {
                return this.peeringASField;
            }
            set {
                this.peeringASField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DatacenterCluster {
        
        private DatacenterClusterCertificate[] certificateField;
        
        private MachinePool[] machinePoolField;
        
        private VIPRange[] vIPRangeField;
        
        private DatacenterClusterSnatRule[] snatRuleField;
        
        private DatacenterClusterDirectIpVlan[] directIpVlanField;
        
        private string nameField;
        
        private string fCCClusterField;
        
        private string datacenterVipRangeField;
        
        private string utilityNodesIpRangeField;
        
        private string dnsServersIpRangeField;
        
        private string privateVipNodesIpRangeField;
        
        private string fabricBackendJumpboxesIpRangeField;
        
        private string monitorNodesIpRangeField;
        
        private string kmsNodesIpRangeField;
        
        private string defaultIpRangeField;
        
        private string xStoreVipsIpRangeField;
        
        private string rdfeSnatsIpRangeField;
        
        private string fcIpRangeField;
        
        private string switchDigiPowerIpRangeField;
        
        private string clusterIdField;
        
        private string ffeVipRangeField;
        
        private string ufcIpRangeField;
        
        private string usingSoftwareLoadBalancerOnlyField;
        
        private string torAsRouterField;
        
        private string fabricPoolNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Certificate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DatacenterClusterCertificate[] Certificate {
            get {
                return this.certificateField;
            }
            set {
                this.certificateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MachinePool")]
        public MachinePool[] MachinePool {
            get {
                return this.machinePoolField;
            }
            set {
                this.machinePoolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VIPRange")]
        public VIPRange[] VIPRange {
            get {
                return this.vIPRangeField;
            }
            set {
                this.vIPRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SnatRule", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DatacenterClusterSnatRule[] SnatRule {
            get {
                return this.snatRuleField;
            }
            set {
                this.snatRuleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DirectIpVlan", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DatacenterClusterDirectIpVlan[] DirectIpVlan {
            get {
                return this.directIpVlanField;
            }
            set {
                this.directIpVlanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FCCCluster {
            get {
                return this.fCCClusterField;
            }
            set {
                this.fCCClusterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DatacenterVipRange {
            get {
                return this.datacenterVipRangeField;
            }
            set {
                this.datacenterVipRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UtilityNodesIpRange {
            get {
                return this.utilityNodesIpRangeField;
            }
            set {
                this.utilityNodesIpRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DnsServersIpRange {
            get {
                return this.dnsServersIpRangeField;
            }
            set {
                this.dnsServersIpRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PrivateVipNodesIpRange {
            get {
                return this.privateVipNodesIpRangeField;
            }
            set {
                this.privateVipNodesIpRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FabricBackendJumpboxesIpRange {
            get {
                return this.fabricBackendJumpboxesIpRangeField;
            }
            set {
                this.fabricBackendJumpboxesIpRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MonitorNodesIpRange {
            get {
                return this.monitorNodesIpRangeField;
            }
            set {
                this.monitorNodesIpRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string KmsNodesIpRange {
            get {
                return this.kmsNodesIpRangeField;
            }
            set {
                this.kmsNodesIpRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DefaultIpRange {
            get {
                return this.defaultIpRangeField;
            }
            set {
                this.defaultIpRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string XStoreVipsIpRange {
            get {
                return this.xStoreVipsIpRangeField;
            }
            set {
                this.xStoreVipsIpRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RdfeSnatsIpRange {
            get {
                return this.rdfeSnatsIpRangeField;
            }
            set {
                this.rdfeSnatsIpRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FcIpRange {
            get {
                return this.fcIpRangeField;
            }
            set {
                this.fcIpRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SwitchDigiPowerIpRange {
            get {
                return this.switchDigiPowerIpRangeField;
            }
            set {
                this.switchDigiPowerIpRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ClusterId {
            get {
                return this.clusterIdField;
            }
            set {
                this.clusterIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FfeVipRange {
            get {
                return this.ffeVipRangeField;
            }
            set {
                this.ffeVipRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UfcIpRange {
            get {
                return this.ufcIpRangeField;
            }
            set {
                this.ufcIpRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UsingSoftwareLoadBalancerOnly {
            get {
                return this.usingSoftwareLoadBalancerOnlyField;
            }
            set {
                this.usingSoftwareLoadBalancerOnlyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TorAsRouter {
            get {
                return this.torAsRouterField;
            }
            set {
                this.torAsRouterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FabricPoolName {
            get {
                return this.fabricPoolNameField;
            }
            set {
                this.fabricPoolNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DatacenterClusterCertificate {
        
        private string pathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DatacenterClusterSnatRule {
        
        private string nameField;
        
        private string typeField;
        
        private string subnetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Subnet {
            get {
                return this.subnetField;
            }
            set {
                this.subnetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DatacenterClusterDirectIpVlan {
        
        private string nameField;
        
        private string machinePoolNamesField;
        
        private string rangeField;
        
        private string routerGatewayField;
        
        private string startIPField;
        
        private string endIPField;
        
        private string startMacField;
        
        private string endMacField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MachinePoolNames {
            get {
                return this.machinePoolNamesField;
            }
            set {
                this.machinePoolNamesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Range {
            get {
                return this.rangeField;
            }
            set {
                this.rangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RouterGateway {
            get {
                return this.routerGatewayField;
            }
            set {
                this.routerGatewayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StartIP {
            get {
                return this.startIPField;
            }
            set {
                this.startIPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EndIP {
            get {
                return this.endIPField;
            }
            set {
                this.endIPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StartMac {
            get {
                return this.startMacField;
            }
            set {
                this.startMacField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EndMac {
            get {
                return this.endMacField;
            }
            set {
                this.endMacField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class NewDataSet {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Datacenter", typeof(Datacenter))]
        [System.Xml.Serialization.XmlElementAttribute("MachinePool", typeof(MachinePool))]
        [System.Xml.Serialization.XmlElementAttribute("VIPRange", typeof(VIPRange))]
        [System.Xml.Serialization.XmlElementAttribute("Vlan", typeof(Vlan))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
}
