//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace UnderstandingReddogDatacenterInfo.DEV {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class MachinePool {
        
        private MachinePoolVlan[] vlanField;
        
        private MachinePoolLoadBalancerSetConfiguration[] loadBalancerSetConfigurationField;
        
        private string nameField;
        
        private string capabilitiesField;
        
        private string fillFactorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Vlan", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MachinePoolVlan[] Vlan {
            get {
                return this.vlanField;
            }
            set {
                this.vlanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LoadBalancerSetConfiguration", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MachinePoolLoadBalancerSetConfiguration[] LoadBalancerSetConfiguration {
            get {
                return this.loadBalancerSetConfigurationField;
            }
            set {
                this.loadBalancerSetConfigurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Capabilities {
            get {
                return this.capabilitiesField;
            }
            set {
                this.capabilitiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FillFactor {
            get {
                return this.fillFactorField;
            }
            set {
                this.fillFactorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class MachinePoolVlan {
        
        private MachinePoolVlanIPRange[] iPRangeField;
        
        private MachinePoolVlanMacRange[] macRangeField;
        
        private LoadBalancerSet[] loadBalancerSetField;
        
        private string nameField;
        
        private string rangeField;
        
        private string routerGatewayField;
        
        private string startIPField;
        
        private string endIPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IPRange", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MachinePoolVlanIPRange[] IPRange {
            get {
                return this.iPRangeField;
            }
            set {
                this.iPRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MacRange", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MachinePoolVlanMacRange[] MacRange {
            get {
                return this.macRangeField;
            }
            set {
                this.macRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LoadBalancerSet")]
        public LoadBalancerSet[] LoadBalancerSet {
            get {
                return this.loadBalancerSetField;
            }
            set {
                this.loadBalancerSetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Range {
            get {
                return this.rangeField;
            }
            set {
                this.rangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RouterGateway {
            get {
                return this.routerGatewayField;
            }
            set {
                this.routerGatewayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StartIP {
            get {
                return this.startIPField;
            }
            set {
                this.startIPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EndIP {
            get {
                return this.endIPField;
            }
            set {
                this.endIPField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class MachinePoolVlanIPRange {
        
        private string startIPField;
        
        private string endIPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StartIP {
            get {
                return this.startIPField;
            }
            set {
                this.startIPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EndIP {
            get {
                return this.endIPField;
            }
            set {
                this.endIPField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class MachinePoolVlanMacRange {
        
        private string startMacField;
        
        private string endMacField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StartMac {
            get {
                return this.startMacField;
            }
            set {
                this.startMacField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EndMac {
            get {
                return this.endMacField;
            }
            set {
                this.endMacField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class LoadBalancerSet {
        
        private LoadBalancerSetLoadBalancer[] loadBalancerField;
        
        private string deviceField;
        
        private string ipField;
        
        private string selfIPsField;
        
        private string locationField;
        
        private string sKUField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LoadBalancer", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LoadBalancerSetLoadBalancer[] LoadBalancer {
            get {
                return this.loadBalancerField;
            }
            set {
                this.loadBalancerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Device {
            get {
                return this.deviceField;
            }
            set {
                this.deviceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IP {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SelfIPs {
            get {
                return this.selfIPsField;
            }
            set {
                this.selfIPsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SKU {
            get {
                return this.sKUField;
            }
            set {
                this.sKUField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class LoadBalancerSetLoadBalancer {
        
        private string nameField;
        
        private string locationField;
        
        private string addressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class MachinePoolLoadBalancerSetConfiguration {
        
        private string nameField;
        
        private string deviceField;
        
        private string vipRangeField;
        
        private string vlanNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Device {
            get {
                return this.deviceField;
            }
            set {
                this.deviceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VipRange {
            get {
                return this.vipRangeField;
            }
            set {
                this.vipRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VlanName {
            get {
                return this.vlanNameField;
            }
            set {
                this.vlanNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Datacenter {
        
        private MachinePool[] machinePoolField;
        
        private DatacenterCluster[] clusterField;
        
        private LoadBalancerSet[] loadBalancerSetField;
        
        private DatacenterRack[] rackField;
        
        private string locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MachinePool")]
        public MachinePool[] MachinePool {
            get {
                return this.machinePoolField;
            }
            set {
                this.machinePoolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cluster", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DatacenterCluster[] Cluster {
            get {
                return this.clusterField;
            }
            set {
                this.clusterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LoadBalancerSet")]
        public LoadBalancerSet[] LoadBalancerSet {
            get {
                return this.loadBalancerSetField;
            }
            set {
                this.loadBalancerSetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Rack", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DatacenterRack[] Rack {
            get {
                return this.rackField;
            }
            set {
                this.rackField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DatacenterCluster {
        
        private MachinePool[] machinePoolField;
        
        private string nameField;
        
        private string descriptionField;
        
        private string defaultIpRangeField;
        
        private string datacenterVipRangeField;
        
        private string monitorNodesIpRangeField;
        
        private string utilityNodesIpRangeField;
        
        private string kmsNodesIpRangeField;
        
        private string dnsServersIpRangeField;
        
        private string xStoreVipsIpRangeField;
        
        private string switchDigiPowerIpRangeField;
        
        private string fcIpRangeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MachinePool")]
        public MachinePool[] MachinePool {
            get {
                return this.machinePoolField;
            }
            set {
                this.machinePoolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DefaultIpRange {
            get {
                return this.defaultIpRangeField;
            }
            set {
                this.defaultIpRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DatacenterVipRange {
            get {
                return this.datacenterVipRangeField;
            }
            set {
                this.datacenterVipRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MonitorNodesIpRange {
            get {
                return this.monitorNodesIpRangeField;
            }
            set {
                this.monitorNodesIpRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UtilityNodesIpRange {
            get {
                return this.utilityNodesIpRangeField;
            }
            set {
                this.utilityNodesIpRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string KmsNodesIpRange {
            get {
                return this.kmsNodesIpRangeField;
            }
            set {
                this.kmsNodesIpRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DnsServersIpRange {
            get {
                return this.dnsServersIpRangeField;
            }
            set {
                this.dnsServersIpRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string XStoreVipsIpRange {
            get {
                return this.xStoreVipsIpRangeField;
            }
            set {
                this.xStoreVipsIpRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SwitchDigiPowerIpRange {
            get {
                return this.switchDigiPowerIpRangeField;
            }
            set {
                this.switchDigiPowerIpRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FcIpRange {
            get {
                return this.fcIpRangeField;
            }
            set {
                this.fcIpRangeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DatacenterRack {
        
        private DatacenterRackNetworkSwitch[] networkSwitchField;
        
        private DatacenterRackSerialServer[] serialServerField;
        
        private DatacenterRackPowerStrip[] powerStripField;
        
        private DatacenterRackBlade[] bladeField;
        
        private string locationField;
        
        private string sKUField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NetworkSwitch", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DatacenterRackNetworkSwitch[] NetworkSwitch {
            get {
                return this.networkSwitchField;
            }
            set {
                this.networkSwitchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SerialServer", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DatacenterRackSerialServer[] SerialServer {
            get {
                return this.serialServerField;
            }
            set {
                this.serialServerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PowerStrip", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DatacenterRackPowerStrip[] PowerStrip {
            get {
                return this.powerStripField;
            }
            set {
                this.powerStripField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Blade", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DatacenterRackBlade[] Blade {
            get {
                return this.bladeField;
            }
            set {
                this.bladeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SKU {
            get {
                return this.sKUField;
            }
            set {
                this.sKUField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DatacenterRackNetworkSwitch {
        
        private string locationField;
        
        private string addressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DatacenterRackSerialServer {
        
        private string locationField;
        
        private string addressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DatacenterRackPowerStrip {
        
        private string locationField;
        
        private string addressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DatacenterRackBlade {
        
        private string locationField;
        
        private string machinePoolField;
        
        private string bladeIPField;
        
        private string bladeIdField;
        
        private string assetField;
        
        private string nIC1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MachinePool {
            get {
                return this.machinePoolField;
            }
            set {
                this.machinePoolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BladeIP {
            get {
                return this.bladeIPField;
            }
            set {
                this.bladeIPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BladeId {
            get {
                return this.bladeIdField;
            }
            set {
                this.bladeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Asset {
            get {
                return this.assetField;
            }
            set {
                this.assetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NIC1 {
            get {
                return this.nIC1Field;
            }
            set {
                this.nIC1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class NewDataSet {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Datacenter", typeof(Datacenter))]
        [System.Xml.Serialization.XmlElementAttribute("LoadBalancerSet", typeof(LoadBalancerSet))]
        [System.Xml.Serialization.XmlElementAttribute("MachinePool", typeof(MachinePool))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
}
