global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: 'icecream-collector-internal-metrics'
    metrics_path: '/metrics'
    scrape_interval: 30s
    static_configs:
    - targets: ['host.docker.internal:18888']
  - job_name: 'icecream-customer-metrics'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
    - targets: ['host.docker.internal:19089']    